### ISSUE TITLE
Unable to have styles on Modal dialog

### ISSUE THREAD

**Issue by ziedHamdi** [dart-league/ng_bootstrap#62] opened 2017-01-19 17:28 UTC
Hi,

I have a very basic use of the lib and it doesn't work:

invite-users-dialog.html
```
[
<bs-modal #inviteUserDialog [header]="'Are you sure?'"
          cancelLabel="cancel"
          positiveLabel="YES"
          negativeLabel="NO"
          [actions]="['POSITIVE', 'NEGATIVE', 'CANCEL']"
          (close)="onModalClose($event)">

  Do you want to save?
  <footer style="display: inline-block;">
    <button class="btn btn-danger" type="button">Destroy</button>
  </footer>
</bs-modal>](url)
```

users.html
```
<div *ngIf="adding" class="addZone">
<invite-users-dialog class="dialog"></invite-users-dialog>
</div>
```

When asked to display thorough show(), the modal shows in a corner inside the users.html component's div, no opacity layer is behind it, and no rounded corners... I have to do it all my self.

The resutling html is the following
```

<div _ngcontent-xlb-7="" class="addZone">
			<invite-users-dialog _ngcontent-xlb-7="" class="dialog" _nghost-xlb-8=""><bs-modal _ngcontent-xlb-8="" cancellabel="cancel" negativelabel="NO" positivelabel="YES">

  Do you want to save?
  <footer _ngcontent-xlb-8="" style="display: inline-block;">
    <button _ngcontent-xlb-8="" class="btn btn-danger" type="button">Destroy</button>
  </footer>
</bs-modal></invite-users-dialog>
		</div>
```

**Comment by luisvt** [comment] 2017-02-28 04:43
Could you elaborate a little bit more the samples. They are incomplete and I cannot reproduce the error you are having.

why the sample you gave before is inside brackets:
```html
[
<bs-modal #inviteUserDialog [header]="'Are you sure?'"
          cancelLabel="cancel"
          positiveLabel="YES"
          negativeLabel="NO"
          [actions]="['POSITIVE', 'NEGATIVE', 'CANCEL']"
          (close)="onModalClose($event)">

  Do you want to save?
  <footer style="display: inline-block;">
    <button class="btn btn-danger" type="button">Destroy</button>
  </footer>
</bs-modal>](url)
```

and what is for `url`?

**Comment by luisvt** [comment] 2017-06-28 15:15
I'm going to close this issue since the user never replied back.

**Closed as completed by luisvt** 2017-06-28 15:15 UTC
